### ISSUE TITLE
all options grayed out

### ISSUE THREAD

**Issue by thisischrys** [maz-1/grub2-editor#3]
Arch user, I'm booting a UEFI system using grub 2.02.beta2-6 and a version of this compiled today, but all options are grayed out. Not sure how to get log output for this, I tried running kcmshell5 grub2 but all that returns is "false"

No other boot managers set in EFI.

**Comment by maz-1** [comment]
Are you trying to run with root priviledge?
I've just fixed a problem with root user, try again.

**Comment by thisischrys** [comment]
no, running as a regular user
tried the latest build, same issue
http://i.imgur.com/KVRj06k.png

**Comment by maz-1** [comment]
Where is your grub.cfg and grubenv?
By default gurb2-editor reads these two files from /boot/grub2 .
UEFI is probably using a different path for grub configurations, use  
<code>cmake -DGRUB_MENU="/path/to/grub.cfg" -DGRUB_ENV="/path/to/grubenv" </code>
to define the path of grub.cfg and grubenv

**Comment by maz-1** [comment]
Currently I don't have a UEFI environment to test it out. It would be good if anyone forks the project and makes it compatible with UEFI.

**Comment by thisischrys** [comment]
I have it in /boot/grub, but I pointed it towards that already.
I have another UEFI system where it works fine, which is what's baffling me.

**Comment by maz-1** [comment]
Should be fixed now.

**Comment by thisischrys** [comment]
indeed it is
