### ISSUE TITLE
release number

### ISSUE THREAD

**Issue by AlmAck** [maz-1/grub2-editor#4]
I was packaging it on Chakra and I saw that you are using the old verion 0.5.8 instead of a newer one (the old official pkg was 0.6.4)
I suggest to give a new version number, like 0.7 or something else.
Is up to you, maybe you want to wait and set a new version number with the first release.

**Comment by maz-1** [comment]
I just added 0.7.0 tag
https://github.com/maz-1/grub2-editor/releases/tag/0.7.0

**Comment by AlmAck** [comment]
Awesome! thank you!
the pkg is already in our repositories (Chakra)
