### ISSUE TITLE
Could not automatically resolve GRUB paths

### ISSUE THREAD

**Issue by groni** [maz-1/grub2-editor#5]
Can you help me i try it to build but i became each Time the same error. I have search at the www but no solving there for it.

cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DLIB_INSTALL_DIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DSYSCONF_INSTALL_DIR=/etc -DBUILD_TESTING=OFF
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/share/colorgcc/cc
-- Check for working C compiler: /usr/share/colorgcc/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/share/colorgcc/c++
-- Check for working CXX compiler: /usr/share/colorgcc/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:324 (message):
  LIB_INSTALL_DIR is deprecated, use KDE_INSTALL_LIBDIR instead.
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:418 (_define_relative)
  CMakeLists.txt:18 (include)

CMake Deprecation Warning at /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:324 (message):
  SYSCONF_INSTALL_DIR is deprecated, use KDE_INSTALL_SYSCONFDIR instead.
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:379 (_define_relative)
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:601 (_define_absolute)
  CMakeLists.txt:18 (include)

-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Found KF5CoreAddons: /usr/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.27.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.7") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.11") 
-- Found KF5I18n: /usr/lib/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.27.0")                   
-- Found KF5Auth: /usr/lib/cmake/KF5Auth/KF5AuthConfig.cmake (found version "5.27.0")                   
-- Found KF5ConfigWidgets: /usr/lib/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.27.0")                                                                                                
-- Found KF5KIO: /usr/lib/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.27.0")                      
-- Found KF5Solid: /usr/lib/cmake/KF5Solid/KF5SolidConfig.cmake (found version "5.27.0")                
-- Found KF5: success (found version "5.27.0") found components:  CoreAddons I18n Auth ConfigWidgets KIO Solid                                                                                                  
CMake Error at cmake/modules/GRUBPaths.cmake:53 (message):                                              
  Could not automatically resolve GRUB paths.  Please specify all of them
  manually.
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)

-- Configuring incomplete, errors occurred!
See also "/home/groni/Downloads/grub2-editor-0.7.0/build/CMakeFiles/CMakeOutput.log".

Many thanks in advanced

**Comment by maz-1** [comment]
What distro are you using? Where did you instal grub to?
I have no problem with ArchLinux x64

**Comment by groni** [comment]
Hi maz-1
I use Pisi Linux and build packages for it.
I have try to build grub2-editor, with Pisi Linux 1.2 works it, but not with Pisi Linux 2.0 with KDE5

Grub is installed in /boot/grub2
I have look  at the AUR Repo and have try it but i become each Time the same error

**Comment by maz-1** [comment]
I know nothing about that distribution, maybe it is using different names for executables in grub.
Anyway you should try to manually define all related cmake variables.
View cmake/modules/GRUBPaths.cmake for all variables that you have to define.

**Comment by groni** [comment]
Short Feedback to you !!!

Grub2-Editor works now with Pisi Linux 2.0

Thanks for your answer and your Help
