### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by SolarAquarion** [maz-1/grub2-editor#9]
[ 30%] Linking CXX shared module kcm_grub2.so
CMakeFiles/kcm_grub2.dir/convertDlg.cpp.o: In function `ConvertDialog::ConvertDialog(QWidget*, QFlags<Qt::WindowType>)':
convertDlg.cpp:(.text+0x4e2): undefined reference to `GetMagickStealth'
CMakeFiles/kcm_grub2.dir/convertDlg.cpp.o: In function `ConvertDialog::slotOkButtonClicked()':
convertDlg.cpp:(.text+0x192f): undefined reference to `Magick::Geometry::Geometry(unsigned long, unsigned long, long, long)'
convertDlg.cpp:(.text+0x1949): undefined reference to `Magick::Geometry::aspect(bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/kcm_grub2.dir/build.make:325: src/kcm_grub2.so]

**Comment by pavbaranov** [comment]
This is probably problem with imagemagick 7.0.7.21. I can confirm it (Arch Linux).

**Comment by maz-1** [comment]
Im not using plasma desktop now, so cant fix it ATM
You can edit CMakeLists.txt to exclude imagemagick for now.

**Comment by SolarAquarion** [comment]
If I created a patch that tries for both ImageMagick versions that may be
on the system

On Feb 2, 2018 10:25 AM, "maz-1" <notifications@github.com> wrote:

Im not using plasma desktop now, so cant fix it ATM
You can edit CMakeLists.txt to exclude imagemagick for now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/maz-1/grub2-editor/issues/9#issuecomment-362603468>,
or mute
the thread

**Comment by maz-1** [comment]
Reference:
https://www.imagemagick.org/script/porting.php
https://www.imagemagick.org/Magick++/Documentation.html

**Comment by SolarAquarion** [comment]
well, i tried imagemagick6 and it's still failing
for which version does it compile properly

**Comment by maz-1** [comment]
fixed
